/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class city_windmill_ingameime_client_jni_ExternalBaseIME */

#ifndef _Included_city_windmill_ingameime_client_jni_ExternalBaseIME
#define _Included_city_windmill_ingameime_client_jni_ExternalBaseIME
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    nInitialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_nInitialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    nUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_nUninitialize
  (JNIEnv *, jobject);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    nSetState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_nSetState
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    nSetFullScreen
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_nSetFullScreen
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    nSetHandleComposition
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_nSetHandleComposition
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
