/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class city_windmill_ingameime_client_jni_ExternalBaseIME */

#ifndef _Included_city_windmill_ingameime_client_jni_ExternalBaseIME
#define _Included_city_windmill_ingameime_client_jni_ExternalBaseIME
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    Initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_Initialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    Uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_Uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    SetState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_SetState
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    SetFullScreen
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_SetFullScreen
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     city_windmill_ingameime_client_jni_ExternalBaseIME
 * Method:    SetHandleComposition
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_city_windmill_ingameime_client_jni_ExternalBaseIME_SetHandleComposition
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
