/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class CandidateListCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CandidateListCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CandidateListCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_CandidateListCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected CandidateListCallback() {
    wrapper = new CandidateListCallbackImpl(){
      public void call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  CandidateListState arg0, CandidateListContext arg1
/*@SWIG@*/) {
    CandidateListCallback.this.call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  arg0, arg1
/*@SWIG@*/);
      }
    };
    proxy = new CandidateListCallback(wrapper);
  }

  static CandidateListCallback makeNative(CandidateListCallback in) {
    if (null == in.wrapper) return in;
    return in.proxy;
  }

  // Both of these are retained to prevent garbage collection from happening too early
  private CandidateListCallbackImpl wrapper;
  private CandidateListCallback proxy;

  public void call(CandidateListState arg0, CandidateListContext arg1) {
    IngameIMEJNI.CandidateListCallback_call(swigCPtr, this, arg0.swigValue(), CandidateListContext.getCPtr(arg1), arg1);
  }

  public CandidateListCallback(CandidateListCallbackImpl in) {
    this(IngameIMEJNI.new_CandidateListCallback(CandidateListCallbackImpl.getCPtr(in), in), true);
  }

}
