/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class CandidateListCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CandidateListCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CandidateListCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_CandidateListCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CandidateListCallback(CandidateListCallback arg0) {
    this(IngameIMEJNI.new_CandidateListCallback__SWIG_0(CandidateListCallback.getCPtr(arg0), arg0), true);
  }

  public void call(CandidateListState arg0, CandidateListContext arg1) {
    IngameIMEJNI.CandidateListCallback_call(swigCPtr, this, arg0.swigValue(), CandidateListContext.getCPtr(arg1), arg1);
  }

  public CandidateListCallback(SWIGTYPE_p_f_q_const__enum_IngameIME__CandidateListState_p_q_const__IngameIME__CandidateListContext__void arg0) {
    this(IngameIMEJNI.new_CandidateListCallback__SWIG_1(SWIGTYPE_p_f_q_const__enum_IngameIME__CandidateListState_p_q_const__IngameIME__CandidateListContext__void.getCPtr(arg0)), true);
  }

  public CandidateListCallback(CandidateListCallbackImpl in) {
    this(IngameIMEJNI.new_CandidateListCallback__SWIG_2(CandidateListCallbackImpl.getCPtr(in), in), true);
  }

}
