/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class CandidateListContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CandidateListContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CandidateListContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CandidateListContext obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_CandidateListContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getSelection() {
    return IngameIMEJNI.CandidateListContext_selection_get(swigCPtr, this);
  }

  public string_list getCandidates() {
    long cPtr = IngameIMEJNI.CandidateListContext_candidates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new string_list(cPtr, false);
  }

}
