/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class CommitCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CommitCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommitCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_CommitCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected CommitCallback() {
    wrapper = new CommitCallbackImpl(){
      public void call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  String arg0
/*@SWIG@*/) {
    CommitCallback.this.call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  arg0
/*@SWIG@*/);
      }
    };
    proxy = new CommitCallback(wrapper);
  }

  static CommitCallback makeNative(CommitCallback in) {
    if (null == in.wrapper) return in;
    return in.proxy;
  }

  // Both of these are retained to prevent garbage collection from happening too early
  private CommitCallbackImpl wrapper;
  private CommitCallback proxy;

  public void call(String arg0) {
    IngameIMEJNI.CommitCallback_call(swigCPtr, this, arg0);
  }

  public CommitCallback(CommitCallbackImpl in) {
    this(IngameIMEJNI.new_CommitCallback(CommitCallbackImpl.getCPtr(in), in), true);
  }

}
