/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class CommitCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CommitCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommitCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CommitCallback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_CommitCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void call(String arg0) {
    IngameIMEJNI.CommitCallback_call(swigCPtr, this, arg0);
  }

  public CommitCallback(CommitCallbackImpl in) {
    this(IngameIMEJNI.new_CommitCallback(CommitCallbackImpl.getCPtr(in), in), true);
  }

}
