/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public final class CompositionState {
  public final static CompositionState Begin = new CompositionState("Begin");
  public final static CompositionState Update = new CompositionState("Update");
  public final static CompositionState End = new CompositionState("End");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CompositionState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CompositionState.class + " with value " + swigValue);
  }

  private CompositionState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CompositionState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CompositionState(String swigName, CompositionState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CompositionState[] swigValues = { Begin, Update, End };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

