/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class InputModeCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InputModeCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputModeCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_InputModeCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InputModeCallback(InputModeCallback arg0) {
    this(IngameIMEJNI.new_InputModeCallback__SWIG_0(InputModeCallback.getCPtr(arg0), arg0), true);
  }

  public void call(InputMode arg0) {
    IngameIMEJNI.InputModeCallback_call(swigCPtr, this, arg0.swigValue());
  }

  public InputModeCallback(SWIGTYPE_p_f_q_const__enum_IngameIME__InputMode__void arg0) {
    this(IngameIMEJNI.new_InputModeCallback__SWIG_1(SWIGTYPE_p_f_q_const__enum_IngameIME__InputMode__void.getCPtr(arg0)), true);
  }

  public InputModeCallback(InputModeCallbackImpl in) {
    this(IngameIMEJNI.new_InputModeCallback__SWIG_2(InputModeCallbackImpl.getCPtr(in), in), true);
  }

}
