/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class InputContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InputContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(InputContext obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_InputContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String getVersion() {
    return IngameIMEJNI.InputContext_Version_get();
  }

  public InputMode getInputMode() {
    return InputMode.swigToEnum(IngameIMEJNI.InputContext_getInputMode(swigCPtr, this));
  }

  public void setPreEditRect(PreEditRect rect) {
    IngameIMEJNI.InputContext_setPreEditRect(swigCPtr, this, PreEditRect.getCPtr(rect), rect);
  }

  public PreEditRect getPreEditRect() {
    return new PreEditRect(IngameIMEJNI.InputContext_getPreEditRect(swigCPtr, this), true);
  }

  public void setActivated(boolean activated) {
    IngameIMEJNI.InputContext_setActivated(swigCPtr, this, activated);
  }

  public boolean getActivated() {
    return IngameIMEJNI.InputContext_getActivated(swigCPtr, this);
  }

  public PreEditCallback setCallback(PreEditCallback callback) {
    return new PreEditCallback(IngameIMEJNI.InputContext_setCallback__SWIG_0(swigCPtr, this, PreEditCallback.getCPtr(callback), callback), true);
  }

  public CommitCallback setCallback(CommitCallback callback) {
    return new CommitCallback(IngameIMEJNI.InputContext_setCallback__SWIG_1(swigCPtr, this, CommitCallback.getCPtr(callback), callback), true);
  }

  public CandidateListCallback setCallback(CandidateListCallback callback) {
    return new CandidateListCallback(IngameIMEJNI.InputContext_setCallback__SWIG_2(swigCPtr, this, CandidateListCallback.getCPtr(callback), callback), true);
  }

  public InputModeCallback setCallback(InputModeCallback callback) {
    return new InputModeCallback(IngameIMEJNI.InputContext_setCallback__SWIG_3(swigCPtr, this, InputModeCallback.getCPtr(callback), callback), true);
  }

}
