/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public final class InputMode {
  public final static InputMode AlphaNumeric = new InputMode("AlphaNumeric");
  public final static InputMode Native = new InputMode("Native");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static InputMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + InputMode.class + " with value " + swigValue);
  }

  private InputMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private InputMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private InputMode(String swigName, InputMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static InputMode[] swigValues = { AlphaNumeric, Native };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

