/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class InputModeCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InputModeCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputModeCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_InputModeCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected InputModeCallback() {
    wrapper = new InputModeCallbackImpl(){
      public void call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  InputMode arg0
/*@SWIG@*/) {
    InputModeCallback.this.call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  arg0
/*@SWIG@*/);
      }
    };
    proxy = new InputModeCallback(wrapper);
  }

  static InputModeCallback makeNative(InputModeCallback in) {
    if (null == in.wrapper) return in;
    return in.proxy;
  }

  // Both of these are retained to prevent garbage collection from happening too early
  private InputModeCallbackImpl wrapper;
  private InputModeCallback proxy;

  public void call(InputMode arg0) {
    IngameIMEJNI.InputModeCallback_call(swigCPtr, this, arg0.swigValue());
  }

  public InputModeCallback(InputModeCallbackImpl in) {
    this(IngameIMEJNI.new_InputModeCallback(InputModeCallbackImpl.getCPtr(in), in), true);
  }

}
