/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class PreEditContext {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PreEditContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PreEditContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_PreEditContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getSelStart() {
    return IngameIMEJNI.PreEditContext_selStart_get(swigCPtr, this);
  }

  public int getSelEnd() {
    return IngameIMEJNI.PreEditContext_selEnd_get(swigCPtr, this);
  }

  public String getContent() {
    return IngameIMEJNI.PreEditContext_content_get(swigCPtr, this);
  }

}
