/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class PreEditCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PreEditCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PreEditCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_PreEditCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PreEditCallback(PreEditCallback arg0) {
    this(IngameIMEJNI.new_PreEditCallback__SWIG_0(PreEditCallback.getCPtr(arg0), arg0), true);
  }

  public void call(CompositionState arg0, PreEditContext arg1) {
    IngameIMEJNI.PreEditCallback_call(swigCPtr, this, arg0.swigValue(), PreEditContext.getCPtr(arg1), arg1);
  }

  public PreEditCallback(SWIGTYPE_p_f_q_const__enum_IngameIME__CompositionState_p_q_const__IngameIME__PreEditContext__void arg0) {
    this(IngameIMEJNI.new_PreEditCallback__SWIG_1(SWIGTYPE_p_f_q_const__enum_IngameIME__CompositionState_p_q_const__IngameIME__PreEditContext__void.getCPtr(arg0)), true);
  }

  public PreEditCallback(PreEditCallbackImpl in) {
    this(IngameIMEJNI.new_PreEditCallback__SWIG_2(PreEditCallbackImpl.getCPtr(in), in), true);
  }

}
