/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class PreEditCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PreEditCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PreEditCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_PreEditCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected PreEditCallback() {
    wrapper = new PreEditCallbackImpl(){
      public void call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  CompositionState arg0, PreEditContext arg1
/*@SWIG@*/) {
    PreEditCallback.this.call(/*@SWIG:E:\Codes\IngameIME_Win32\IngameIME-Common\src\std_function.i,25,FOR_EACH@*/ 
  arg0, arg1
/*@SWIG@*/);
      }
    };
    proxy = new PreEditCallback(wrapper);
  }

  static PreEditCallback makeNative(PreEditCallback in) {
    if (null == in.wrapper) return in;
    return in.proxy;
  }

  // Both of these are retained to prevent garbage collection from happening too early
  private PreEditCallbackImpl wrapper;
  private PreEditCallback proxy;

  public void call(CompositionState arg0, PreEditContext arg1) {
    IngameIMEJNI.PreEditCallback_call(swigCPtr, this, arg0.swigValue(), PreEditContext.getCPtr(arg1), arg1);
  }

  public PreEditCallback(PreEditCallbackImpl in) {
    this(IngameIMEJNI.new_PreEditCallback(PreEditCallbackImpl.getCPtr(in), in), true);
  }

}
