/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class PreEditCallbackImpl {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PreEditCallbackImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PreEditCallbackImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PreEditCallbackImpl obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_PreEditCallbackImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    IngameIMEJNI.PreEditCallbackImpl_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    IngameIMEJNI.PreEditCallbackImpl_change_ownership(this, swigCPtr, true);
  }

  protected void call(CompositionState arg0, PreEditContext arg1) {
    IngameIMEJNI.PreEditCallbackImpl_call(swigCPtr, this, arg0.swigValue(), PreEditContext.getCPtr(arg1), arg1);
  }

  public PreEditCallbackImpl() {
    this(IngameIMEJNI.new_PreEditCallbackImpl(), true);
    IngameIMEJNI.PreEditCallbackImpl_director_connect(this, swigCPtr, true, true);
  }

}
