/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ingameime;

public class string_list extends java.util.AbstractSequentialList<String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected string_list(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(string_list obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(string_list obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IngameIMEJNI.delete_string_list(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public string_list(java.util.Collection c) {
    this();
    java.util.ListIterator<String> it = listIterator(0);
    // Special case the "copy constructor" here to avoid lots of cross-language calls
    for (java.lang.Object o : c) {
      it.add((String)o);
    }
  }

  public int size() {
    return doSize();
  }

  public boolean add(String value) {
    addLast(value);
    return true;
  }

  public java.util.ListIterator<String> listIterator(int index) {
    return new java.util.ListIterator<String>() {
      private Iterator pos;
      private Iterator last;

      private java.util.ListIterator<String> init(int index) {
        if (index < 0 || index > string_list.this.size())
          throw new IndexOutOfBoundsException("Index: " + index);
        pos = string_list.this.begin();
	pos = pos.advance_unchecked(index);
        return this;
      }

      public void add(String v) {
        // Technically we can invalidate last here, but this makes more sense
        last = string_list.this.insert(pos, v);
      }

      public void set(String v) {
        if (null == last) {
          throw new IllegalStateException();
        }
        last.set_unchecked(v);
      }

      public void remove() {
        if (null == last) {
          throw new IllegalStateException();
        }
        string_list.this.remove(last);
        last = null;
      }

      public int previousIndex() {
        return string_list.this.doPreviousIndex(pos);
      }

      public int nextIndex() {
        return string_list.this.doNextIndex(pos);
      }

      public String previous() {
        if (previousIndex() < 0) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.previous_unchecked();
        return last.deref_unchecked();
      }

      public String next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.next_unchecked();
        return last.deref_unchecked();
      }

      public boolean hasPrevious() {
        // This call to previousIndex() will be much slower than the hasNext() implementation, but it's simpler like this with C++ forward iterators
        return previousIndex() != -1;
      }

      public boolean hasNext() {
        return string_list.this.doHasNext(pos);
      }
    }.init(index);
  }

  static public class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IngameIMEJNI.delete_string_list_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void set_unchecked(String v) {
      IngameIMEJNI.string_list_Iterator_set_unchecked(swigCPtr, this, v);
    }
  
    public string_list.Iterator next_unchecked() {
      return new string_list.Iterator(IngameIMEJNI.string_list_Iterator_next_unchecked(swigCPtr, this), true);
    }
  
    public string_list.Iterator previous_unchecked() {
      return new string_list.Iterator(IngameIMEJNI.string_list_Iterator_previous_unchecked(swigCPtr, this), true);
    }
  
    public String deref_unchecked() {
      return IngameIMEJNI.string_list_Iterator_deref_unchecked(swigCPtr, this);
    }
  
    public string_list.Iterator advance_unchecked(long index) {
      return new string_list.Iterator(IngameIMEJNI.string_list_Iterator_advance_unchecked(swigCPtr, this, index), true);
    }
  
  }

  public string_list() {
    this(IngameIMEJNI.new_string_list__SWIG_0(), true);
  }

  public string_list(string_list other) {
    this(IngameIMEJNI.new_string_list__SWIG_1(string_list.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return IngameIMEJNI.string_list_isEmpty(swigCPtr, this);
  }

  public void clear() {
    IngameIMEJNI.string_list_clear(swigCPtr, this);
  }

  public string_list.Iterator remove(string_list.Iterator pos) {
    return new string_list.Iterator(IngameIMEJNI.string_list_remove(swigCPtr, this, string_list.Iterator.getCPtr(pos), pos), true);
  }

  public void removeLast() {
    IngameIMEJNI.string_list_removeLast(swigCPtr, this);
  }

  public void removeFirst() {
    IngameIMEJNI.string_list_removeFirst(swigCPtr, this);
  }

  public void addLast(String value) {
    IngameIMEJNI.string_list_addLast(swigCPtr, this, value);
  }

  public void addFirst(String value) {
    IngameIMEJNI.string_list_addFirst(swigCPtr, this, value);
  }

  private string_list.Iterator begin() {
    return new string_list.Iterator(IngameIMEJNI.string_list_begin(swigCPtr, this), true);
  }

  public string_list.Iterator end() {
    return new string_list.Iterator(IngameIMEJNI.string_list_end(swigCPtr, this), true);
  }

  private string_list.Iterator insert(string_list.Iterator pos, String value) {
    return new string_list.Iterator(IngameIMEJNI.string_list_insert(swigCPtr, this, string_list.Iterator.getCPtr(pos), pos, value), true);
  }

  public string_list(int count, String value) {
    this(IngameIMEJNI.new_string_list__SWIG_2(count, value), true);
  }

  private int doSize() {
    return IngameIMEJNI.string_list_doSize(swigCPtr, this);
  }

  private int doPreviousIndex(string_list.Iterator pos) {
    return IngameIMEJNI.string_list_doPreviousIndex(swigCPtr, this, string_list.Iterator.getCPtr(pos), pos);
  }

  private int doNextIndex(string_list.Iterator pos) {
    return IngameIMEJNI.string_list_doNextIndex(swigCPtr, this, string_list.Iterator.getCPtr(pos), pos);
  }

  private boolean doHasNext(string_list.Iterator pos) {
    return IngameIMEJNI.string_list_doHasNext(swigCPtr, this, string_list.Iterator.getCPtr(pos), pos);
  }

}
